site_name: Linux 银河漫游指南
repo_url: https://github.com/linuxhitchhiker/THGLG
edit_uri: edit/main/docs/
copyright: "© 2022 Linux 银河漫游指南贡献者"

nav:
  - 开始:
      - 欢迎: "index.md"
      - 切换到Linux: "prologue/switch-to-linux.md"
      - 寻求帮助:
          - 常见问题: "help/faq.md"
          - 联系我们: "help/contact.md"
  - 安装:
      - Fedora 安装指南: "installation/fedora-installation-guide.md"
      - openSUSE 安装指南: "installation/opensuse-installation-guide.md"
  - 软件:
      - 浏览器: software/browser.md
      - 即时通讯: software/instant-messaging.md
  - 系统配置:
      - HiDPI: config/hidpi.md
  - 进阶:
      - 打包:
          - "advanced/packaging/flatpak.md"
  - 关于:
      - 简介: "about/introduction.md"
      - 许可协议: 'about/license.md'
      - 贡献指南: "about/contributing/guide.md"

theme:
  name: material
  language: zh
  custom_dir: overrides
  locale: zh_CN
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.tabs
plugins:
  - search:
      lang: zh
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - def_list
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify #保证中文链接

extra_css:
  - stylesheets/extra.css
