site_name: Linux 银河漫游指南
repo_url: https://github.com/linuxhitchhiker/THGLG
edit_uri: edit/main/docs/
copyright: "© 2022 Linux 银河漫游指南贡献者，在 CC BY-SA 4.0 下提供。"

nav:
  - 开始:
      - 欢迎: "index.md"
  - 初级:
      - 序言:
          - "basic/prologue/switch-to-linux.md"
      - 安装系统:
          - Fedora 安装指南: "basic/installation/fedora-installation-guide.md"
          - openSUSE 安装指南: "basic/installation/opensuse-installation-guide/opensuse-installation-guide.md"
      - 使用桌面环境:
          - 安装软件: "TBD"
  - 进阶:
      - 使用命令行: "advanced/using-commandline.md"
      - 打包:
          - "advanced/packaging/flatpak.md"
  - 解决方案:
      - 软件:
          - 浏览器: solution/software/browser.md
          - 即时通讯: solution/software/instant-messaging.md
      - 系统配置:
          - HiDPI: config/hidpi.md
  - 寻求帮助:
      - 常见问题: "help/faq.md"
      - 联系我们: "help/contact.md"
  - 关于:
      - 简介: "about/introduction.md"
      - 许可协议: "about/license/index.md"
      - 贡献指南: "about/contributing/index.md"

theme:
  name: material
  language: zh
  custom_dir: overrides
  locale: zh_CN
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.tabs
plugins:
  - search:
      lang: zh
markdown_extensions:
  - abbr
  - md_in_html
  - footnotes
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - def_list
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify #保证中文链接


extra_css:
  - assets/stylesheets/extra.css
