site_name: Linux 银河漫游指南
repo_url: https://github.com/linuxhitchhiker/THGLG
edit_uri: edit/main/docs/
copyright: "© 2022 Linux 银河漫游指南贡献者，在 CC-BY-SA 4.0 下提供。"

nav:
  - 主页:
      - 欢迎: "index.md"
      - 简介: "intro.md"
  - 入门指南:
      - 序言:
          - 切换到 Linux: "entry/prologue/switch-to-linux.md"
          - Linux 发行版: "entry/prologue/choose-distro.md"
          - 桌面环境简介: "entry/prologue/desktop-environment.md"
      - 安装系统:
          - 安装前准备: "entry/installation/pre-install.md"
          - 虚拟机: "entry/installation/virtual-machine.md"
          - Fedora 安装指南: "entry/installation/fedora.md"
          - Fedora Silverblue 安装指南: "entry/installation/fedora-silverblue.md"
          - openSUSE 安装指南: "entry/installation/opensuse.md"
          - Kubuntu 安装指南: "entry/installation/kubuntu.md"
      - 使用桌面环境:
          - 安装软件（图形化界面）: "entry/desktop/apps-gui.md"
  - 进阶教程:
      - 使用命令行:
          - "advanced/shell/index.md"
          - "advanced/shell/base1.md"
          - "advanced/shell/base2.md"
          - "advanced/shell/base3.md"
          - "advanced/shell/base4.md"
          - "advanced/shell/base5.md"
      - 配置系统:
          - "advanced/systemctl/index.md"
          - "advanced/systemctl/update-sys.md"
      - 再次入门:
          - 概述: "advanced/re-entry/index.md"
          - 选择发行版: "advanced/re-entry/distro.md"
          - 软件源与镜像源: "advanced/re-entry/repo-and-mirror.md"
          - 扩展阅读: "advanced/re-entry/extend.md"
  - 高级教程:
      - 打包: "poweruser/packaging/flatpak.md"
  - 解决方案:
      - 系统美化: 
          - 概述: solution/eyecandy/index.md
          - KDE 美化: solution/eyecandy/eyecandy-kde.md
          - Xfce4 美化: solution/eyecandy/eyecandy-xfce4.md
      - 软件:
          - 概述: solution/software/index.md
          - 浏览器: solution/software/browser.md
          - 即时通讯: solution/software/instant-messaging.md
          - Appimage: solution/software/appimage-base.md
      - 系统配置:
          - 概述: solution/config/index.md
          - HiDPI: solution/config/hidpi.md
  - 寻求帮助:
      - 常见问题: "help/faq.md"
      - 如何提问: "help/howto-ask-for-help.md"
      - 联系我们: "help/contact.md"
  - 关于:
      - 简介: "about/index.md"
      - 许可协议: "about/license/index.md"
      - 贡献指南: "about/contributing/index.md"

theme:
  name: material
  language: zh
  custom_dir: overrides
  locale: zh_CN
  palette:
    primary: blue
    accent: blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs

plugins:
  - git-revision-date-localized:
      type: iso_date
      enable_creation_date: true
      exclude:
        - index.md
        - "intro.md"
        - about/*
  - search:
      lang: zh

markdown_extensions:
  - def_list
  - abbr
  - md_in_html
  - footnotes
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - def_list
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify #保证中文链接


# extra_css:
#   - assets/stylesheets/extra.css
